//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_scedule
    {
        public System.DateTime clinic_time { get; set; }
        public System.DateTime hospital_time { get; set; }
        public string is_avalible { get; set; }
        public string Clinic_day { get; set; }
        public string hospial_day { get; set; }
        public string doctor_id { get; set; }
        public Nullable<System.DateTime> clinic_end_time { get; set; }
        public Nullable<System.DateTime> hospital_end_time { get; set; }
    }
}
