//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_request
    {
        public System.TimeSpan Hospital_time { get; set; }
        public System.DateTime date { get; set; }
        public string is_request { get; set; }
        public string patient_name { get; set; }
        public string Hospital_day { get; set; }
        public string Request_Status { get; set; }
        public string doctor_id { get; set; }
    }
}
